### ISSUE TITLE
背景画像の回転配置

### ISSUE THREAD

**Issue by Voyagerflyby** [KMimura/RPGGame#6]
#5 
例えば片側が草原、もう片側が砂利道のような素材を作成した場合
![grass_left_dot](https://user-images.githubusercontent.com/30005000/57194257-d36a4e80-6f7f-11e9-8e56-c95bd9b4302d.png)
上下左右4種類の素材を作るべきか？それとも1種類作っておけば回転しての配置が可能か？

**Comment by KMimura** [comment]
回転させることは難しそう。
もしそのような素材が必要な場合、四種類作ってもらいたいです
